create keyspace if not exists logbooktest with replication = {'class' : 'SimpleStrategy', 'replication_factor' : 1};

create table logbooktest.position (
   date date,
   time time,
   x double, 
   y double,
   z double,
   speed double,
   attack_angle double,
   direction_angle double,  
   PRIMARY KEY (date, time));

create table logbooktest.control_action (
   date date,
   time time,
   mac_address blob, 
   user_id blob,
   command text,
   params text,
   result text,
   PRIMARY KEY (date, time));

create table logbooktest.sensor_data (
   date date,
   time time,
   source_id blob, 
   event text,
   value_name text,
   value double,
   units text,
   PRIMARY KEY (date, time));

create table logbooktest.shift_state (
   date date,
   time time,
   shift_id blob, 
   warning_level text,
   remaining_cartridges tinyint,
   remaining_air tinyint,
   remaining_electricity tinyint,
   comment text,
   PRIMARY KEY (date, time));

create table logbooktest.system_test (
   date date,
   time time,
   system_id blob, 
   result tinyint,
   PRIMARY KEY (date, time));

create table logbooktest.operation_state (
   date date,
   time time,
   boat_id blob, 
   operation_id blob,
   operation_status text,
   distance_to_the_ship double,
   zenith double,
   azimuth double,
   hydrogenium double,
   helium double,
   lithium double,
   beryllium double,
   borum double,
   carboneum double,
   nitrogenium double,
   oxygenium double,
   fluorum double,
   neon double,
   natrium double,
   magnesium double,
   aluminium double,
   silicium double,
   phosphorus double,
   sulfur double,
   chlorum double,
   argon double,
   kalium double,
   calcium double,
   scandium double,
   titanium double,
   vanadium double,
   chromium double,
   manganum double,
   ferrum double,
   cobaltum double,
   niccolum double,
   cuprum double,
   zincum double,
   gallium double,
   germanium double,
   arsenicum double,
   selenium double,
   bromum double,
   crypton double,
   rubidium double,
   strontium double,
   yttrium double,
   zirconium double,
   niobium double,
   molybdaenum double,
   technetium double,
   ruthenium double,
   rhodium double,
   palladium double,
   argentum double,
   cadmium double,
   indium double,
   stannum double,
   stibium double,
   tellurium double,
   iodium double,
   xenon double,
   caesium double,
   barium double,
   lanthanum double,
   cerium double,
   praseodymium double,
   neodymium double,
   promethium double,
   samarium double,
   europium double,
   gadolinium double,
   terbium double,
   dysprosium double,
   holmium double,
   erbium double,
   thulium double,
   ytterbium double,
   lutetium double,
   hafnium double,
   tantalum double,
   wolframium double,
   rhenium double,
   osmium double,
   iridium double,
   platinum double,
   aurum double,
   hydrargyrum double,
   thallium double,
   plumbum double,
   bismuthum double,
   polonium double,
   astatum double,
   radon double,
   francium double,
   radium double,
   actinium double,
   thorium double,
   protactinium double,
   uranium double,
   neptunium double,
   plutonium double,
   americium double,
   curium double,
   berkelium double,
   californium double,
   einsteinium double,
   fermium double,
   mendelevium double,
   nobelium double,
   lawrencium double,
   rutherfordium double,
   dubnium double,
   seaborgium double,
   bohrium double,
   hassium double,
   meitnerium double,
   darmstadtium double,
   roentgenium double,
   copernicium double,
   nihonium double,
   flerovium double,
   moscovium double,
   livermorium double,
   tennessium double,
   oganesson double,
   comment text,
   PRIMARY KEY (date, time));